name: Code Scanning

on:
  workflow_dispatch: # run on request (no need for PR)
  schedule:
    # every UTC 6PM from Mon to Fri
    - cron: "0 18 * * 1-5"

jobs:
  Snyk-scan:
    runs-on: [self-hosted, linux, x64]
    permissions:
      security-events: write
    steps:
      - name: CHECKOUT REPOSITORY
        uses: actions/checkout@v3
      - name: Install Tox
        run: python -m pip install tox
      - name: SNYK SCANNING
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          SNYK_ENDPOINT: ${{ secrets.SNYK_ENDPOINT }}
        continue-on-error: true
        run: tox -e snyk-scan
      - name: UPLOAD TO SECURITY ADVISORIES
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: .tox/snyk.sarif
      - name: UPLOAD REPORT
        uses: actions/upload-artifact@v3
        with:
          path: .tox/snyk.html
        # Use always() to always run this step to publish scan results when there are test failures
        if: ${{ always() }}
